import bcrypt from "bcrypt";
import { encode, decode } from "next-auth/jwt";
import { prisma } from "@/lib/prisma";
import { AppError } from "@/lib/error-handler";
import type { RegisterInput, LoginInput } from "@/validators/auth.schema";

export interface UserInfo {
  id: string;
  name: string;
  email: string;
}

const BCRYPT_SALT_ROUNDS = 10;
const JWT_MAX_AGE = 24 * 60 * 60; // 24 hours in seconds

/**
 * Set of invalidated tokens (in-memory for simplicity).
 * In production, use Redis or a database table for token blacklisting.
 */
const invalidatedTokens = new Set<string>();

/**
 * Auth service implementing registration, login, logout, and session validation.
 */
export const authService = {
  /**
   * Register a new user.
   * Hashes password with bcrypt and creates a user record with UUID.
   * Returns the created user info (without password).
   */
  async register(
    data: RegisterInput
  ): Promise<{ id: string; name: string; email: string }> {
    const { name, email, password } = data;

    // Check if email already exists
    const existingUser = await prisma.user.findUnique({
      where: { email },
    });

    if (existingUser) {
      throw new AppError(400, "A user with this email already exists");
    }

    // Hash password with bcrypt
    const hashedPassword = await bcrypt.hash(password, BCRYPT_SALT_ROUNDS);

    // Create user record (UUID is auto-generated by Prisma/PostgreSQL)
    const user = await prisma.user.create({
      data: {
        name,
        email,
        password: hashedPassword,
      },
      select: {
        id: true,
        name: true,
        email: true,
      },
    });

    return user;
  },

  /**
   * Authenticate a user with email and password.
   * Returns a JWT token and user info on success.
   */
  async login(
    data: LoginInput
  ): Promise<{ token: string; user: UserInfo }> {
    const { email, password } = data;

    // Find user by email
    const user = await prisma.user.findUnique({
      where: { email },
    });

    if (!user) {
      throw new AppError(401, "Invalid email or password");
    }

    // Verify password
    const isValid = await bcrypt.compare(password, user.password);
    if (!isValid) {
      throw new AppError(401, "Invalid email or password");
    }

    // Generate JWT token with 24-hour expiry
    const token = await encode({
      token: {
        id: user.id,
        name: user.name,
        email: user.email,
      },
      secret: process.env.NEXTAUTH_SECRET || "development-secret",
      maxAge: JWT_MAX_AGE,
    });

    return {
      token,
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
      },
    };
  },

  /**
   * Invalidate a session token.
   * Adds the token to the blacklist. Idempotent — calling multiple times is safe.
   */
  async logout(token: string): Promise<void> {
    invalidatedTokens.add(token);
  },

  /**
   * Validate a session token.
   * Returns user info if token is valid and not invalidated, null otherwise.
   */
  async validateSession(token: string): Promise<UserInfo | null> {
    // Check if token has been invalidated
    if (invalidatedTokens.has(token)) {
      return null;
    }

    try {
      const decoded = await decode({
        token,
        secret: process.env.NEXTAUTH_SECRET || "development-secret",
      });

      if (!decoded || !decoded.id || !decoded.email || !decoded.name) {
        return null;
      }

      return {
        id: decoded.id as string,
        name: decoded.name as string,
        email: decoded.email as string,
      };
    } catch {
      return null;
    }
  },

  /**
   * Check if a token has been invalidated (for testing purposes).
   */
  isTokenInvalidated(token: string): boolean {
    return invalidatedTokens.has(token);
  },

  /**
   * Clear all invalidated tokens (for testing purposes).
   */
  clearInvalidatedTokens(): void {
    invalidatedTokens.clear();
  },
};
